Various fixes

diff --git a/deployment/docker/update-psi-j-testing-service b/deployment/docker/update-psi-j-testing-service
--- a/deployment/docker/update-psi-j-testing-service
+++ b/deployment/docker/update-psi-j-testing-service
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
+
 try() {
     N=$1
     shift
@@ -64,7 +66,7 @@ if [ "${PACKAGE::1}" == "/" ]; then
     # install from source
     echo "Installing from source in $PACKAGE"
 elif ! wget -q --method=HEAD "$PACKAGE"; then
-    echo "Error: no such version. Please check that the repo has a 'v$TARGET_VERSION' tag"
+    echo "Error: failed to download $PACKAGE. Please check that the repo has a 'v$TARGET_VERSION' tag"
     exit 2
 fi
 
@@ -115,9 +117,6 @@ doUpgrade_0_4_0() {
         echo "Error. No secrets.json file found for the service."
         exit 1
     fi
-    PACKAGE_LOC=`pip show $PACKAGE_NAME | grep "Location: " | sed 's/Location: //'`
-    makeLink "$PACKAGE_LOC/psij/web/instance/customization.js"
-    makeLink "/etc/psij-testing-service/config.json"
 }
 
 doUpgrades() {
@@ -139,6 +138,10 @@ doUpgrades() {
 
 if [ "$ANSWER" == "y" ]; then
     pip install "$PACKAGE"
+
+    PACKAGE_LOC=`pip show $PACKAGE_NAME | grep "Location: " | sed 's/Location: //'`
+    makeLink "$PACKAGE_LOC/psij/web/instance/customization.js"
+    makeLink "/etc/psij-testing-service/config.json"
 
     try 3 timeout 10s service psi-j-testing-service stop
     doUpgrades
